### ISSUE TITLE
Enhancement: CalciteActionBar groups should be responsive in some manner

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#286]
### Description

Enhancement: CalciteActionBar groups should be responsive in some manner #286

### Helpful Details

Currently, the calcite-action-bar isn't responsive to window height so if the window height is small then the other actions at the bottom are cut off.

**Comment by driskull** [comment]
![action-bar-responsive](https://user-images.githubusercontent.com/1231455/65284189-b2009e00-daed-11e9-8551-2a4ba9bb9551.gif)

cc @kevindoshier incase he is notified of this.

**Comment by asangma** [comment]
@driskull would we collapse to a `...` and on clicking that, use an ActionPad?

**Comment by driskull** [comment]
@asangma would each group be collapsed?

**Comment by driskull** [comment]
What if each group acted like an tab (and had its own icon) if all being open doesn't fit?

Each group would need an icon configured for this though.

**Comment by asangma** [comment]
It's a good idea. Will be interesting for Map Viewer Beta team to figure out those icons.
TBH, a lot of this would be solve by moving some of the buttons to the right action-bar. 😬

**Comment by jcfranco** [comment]
Using https://esri.github.io/calcite-app-components/demos/calcite-action-bar.html, I decreased the height of the action bar container and a scroll bar appears when sized too small. @asangma @driskull Can either of you confirm this is the expected behavior?

<img width="93" alt="Screen Shot 2019-10-02 at 12 48 09 PM" src="https://user-images.githubusercontent.com/197440/66076585-00149900-e513-11e9-935a-5a6938499f99.png">

**Comment by driskull** [comment]
Yes, this is expected for now. Until we can come up with a better way to responsively handle when icons don't all fit.

**Comment by jcfranco** [comment]
Thanks! Closing as verified then.
