### ISSUE TITLE
Bug: calcite-panel header spacing

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#366]
### Summary

Once I upgraded to 4.1.0 the header spacing inside my flow-item is not correct anymore.
Matt noticed that if you add a header action it's fine.

old:
![3](https://user-images.githubusercontent.com/44481292/66525005-e6da9200-eaa8-11e9-8f90-9a97308de7de.png)

new:
![2](https://user-images.githubusercontent.com/44481292/66524987-dcb89380-eaa8-11e9-88d3-90a6322197b0.png)

### Reproduction Steps

https://energy.mapsdevext.arcgis.com/apps/mapviewer/index.html

**Comment by driskull** [comment]
@asangma this seems to be an issue in the `calcite-panel`. The header without a button on the left or right needs more padding.

**Comment by asangma** [comment]
Yeah...right now, the Action is defining the header height. I'll figure a good way to consistently but dynamically set the height.

**Comment by asangma** [comment]
@driskull Do you think we could redo the **panel** header so that it matches the **flow-item** header structure/props?

Right now they're similar in layout but different in how they are put together.

This may be moot depending on the answer to this question: does **panel** need both leading and trailing header content? Seems like our use cases here are for putting stuff in the popover in which case we'd only need a default trailing X action.

Maybe I'm missing something...?

**Comment by asangma** [comment]
I realize this is a different issue. For now I can just add a min-height to headers.

**Comment by driskull** [comment]
> Do you think we could redo the panel header so that it matches the flow-item header structure/props?

It does :)

The flow-item uses the panel inside of it. The reason for the leading button is the back arrow action.

**Comment by asangma** [comment]
@driskull LOL...I see

**Comment by AdelheidF** [comment]
Looks good now.
