### ISSUE TITLE
Enhancement: add "padded" prop to Panel and Block

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#457]
### Description
In order to work better with other components, Block and Panel had default padding removed.
I propose adding a property ("padded") that would allow dev users to opt in to padding.

### Acceptance Criteria 
A prop that can be used to add standard padding to a content area.

#### Desired New Behavior
A prop that can be used to add standard padding to a content area.

#### Desired Change to Look and Feel
Opt-in padding.

**Which Component:**
- [ ] Block
- [ ] Panel

**Example Use Case:**
User is putting stuff other than e.g. pick-list or value-list into a Block or Panel.

cc @AdelheidF

**Comment by asangma** [comment]
re #454

**Comment by pr3tori4n** [comment]
I have some concerns, not with your proposed solution but with the trajectory this sort of thing puts us on.

My first question is: Can't Adelheide add a class and put some padding on the thing? Is this something that needs to be added to the component itself?

In the short term, adding "padded" would work solve this 1 issue. 

My main concern with this approach (from an overall component architecture perspective) is that we'll end up being asked for many variants to fit the different app use cases. I fear the props on these components will bloat to having things like "padded, bordered, margined, etc." In other words, is this just the tip of the iceberg when it comes to these kind of requests?

When we last met, we discussed locking down the variants for the purpose of design purity. But if in practice the apps need some more flexibility when it comes to applying some styling to our components we may need to revisit that stance. 

It will end up painful for us if we architect it to be rigid, but we end up responding to requests for flexibility for several minor issues like this. We can't "componentize" different spacing needs effectively - what happens if a third option is needed - do we end up with 1) noPadding 2) padded 3) paddedMore?

One approach we may consider if the apps are going to need more flexibility is providing some predefined CSS variables and/or classes. We can discuss more if this idea seems interesting.

**Comment by pr3tori4n** [comment]
Another approach may be to create a "container" component, and omit the border/background and other boundaries from the other components. That way we can create a highly configurable container, without it having to be baked into each other component directly.

**Comment by AdelheidF** [comment]
My problem currently is that some components apply padding and some don't and I can't overwrite these. Look at the sample below.

'Show feature with no values' and 'Include in legend' are simple divs that I now applied some padding to (after default padding got removed).
'Classify data' should appear with the exact same look but because it's now a `calcite-block-section` (when you switch it on it opens content) it gets all that padding that I don't want here. And I can't find a way to remove it. It's too much padding which shrinks down usable space.

![image](https://user-images.githubusercontent.com/44481292/67511006-de5a8d80-f64a-11e9-9e9a-9a737826b164.png)

To fix this in the current state I have to apply that wide padding to my entire panel to make it look the same and then I loose a lot of space. Or I most likely will get rid of `calcite-block-section` and do it my own way again.

**Comment by asangma** [comment]
@AdelheidF Thanks. We want to make it work for you. @pr3tori4n and I spoke, and we will be adding a property that will help out.

Hold off on doing it yourself for now. I think we should solve this.

**Comment by pr3tori4n** [comment]
Spoke with @asangma. Ok with going with a simple solution for this. May need to adopt a different pattern later. We'll evaluate as things go.

**Comment by asangma** [comment]
This does not seem to be a problem anymore.
