### ISSUE TITLE
Bug: Setting focus to a calcite-action, doesnt set it to the button, need to tab again to get to the button

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-app-components#475]
### Summary
 Setting focus to a calcite-action, doesnt set it to the button, need to tab again to get to the button
### Expected Behavior
Setting focus to a calcite-action sets the focus to the button in the shadow dom, that way Enter key etc will work as expected
### Reproduction Steps

1.

**Comment by driskull** [comment]
Unfortunately, we can't fix until one of these issues are addressed:

https://github.com/ionic-team/stencil/issues/1008
https://github.com/ionic-team/stencil/issues/1623

OR

Stencil allows us to extend a button directly.

@kevindoshier can you focus on the item through the `element.shadowRoot`?

---

https://developers.google.com/web/fundamentals/web-components/shadowdom#focus

Because we have to have a button within the `<host>` and the host doesn't act like a button, we have this issue.

If we could delegate the focus to the button then I think it wouldn't be an issue.

**Comment by driskull** [comment]
Installed. Will be on next release. The `calcite-action` will now have a `setFocus()` method.

**Comment by kat10140** [comment]
verified!
