### ISSUE TITLE
Enhancement: Add property to ShellPanel that allows content to "float"

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-app-components#590]
### Description
Add a Prop to ShellPanel that will cause this component's `content` node to behave like a "floating panel" without affecting existing usage.

![image](https://user-images.githubusercontent.com/12503298/69577664-b466f480-0f83-11ea-8881-f102333a7464.png)

### Acceptance Criteria 
* Default behavior is as-is
* Prop to activate this appearance
* No change to current implementation
* include scale property for height

### Relevant Info 
This will benefit from the #262 .

#### Which Component
ShellPanel

### Example of unused space in the left panel.
![image](https://user-images.githubusercontent.com/12503298/69578017-73231480-0f84-11ea-8c2d-188c5f920140.png)

#### Example of panel only using as much space as neede.
Show more of the map when the content node can be shorter.
![image](https://user-images.githubusercontent.com/12503298/69579380-37d61500-0f87-11ea-8fde-a1fee49c41ad.png)

**Comment by arjavbadjatiya** [comment]
@asangma  While this change will partly addresses the feedback we have received about the map area, I don't think it'll be enough. The feedback was typically for situations where multiple panels and popouts are open and reduce the visible area of the map. 
![Current](https://user-images.githubusercontent.com/29237960/69585743-63f89280-0f95-11ea-84fd-b9d0931a10c6.png)

   I spoke to @mitc7862  briefly when we had the map viewer usability issues sync about these ideas: 
- For the case of preserving map area when user is a few steps into a process with multiple panels open, we can utilize our **existing drill-in pattern and existing panels** to maintain the view of the map. 

How it could work:  
![Possible option](https://user-images.githubusercontent.com/29237960/69585745-6b1fa080-0f95-11ea-821f-b3f8fcba1b58.png)


And what we would need to do for it:
![Possible option described](https://user-images.githubusercontent.com/29237960/69585756-707ceb00-0f95-11ea-8dd7-5ab62b3e59bd.png)

- Additionally, our general UX goal should be to **minimize scrolling.** So in situations like the fill/outline panel it should be expanded as much as possible from the get go to house the components and cause minimal scrolling when some of the internal components are expanded (irrespective of whether it is a floating panel or drill-in)

- In cases where our goal is to **preserve visible map area**, we should rely on drill-in patterns so that only a fixed amount of space is taken by workflow panels. This should happen with the rich text editor (if possible), styling popouts etc. 

- Also as we discussed briefly the other day, we can look into providing an **alternative exit route** from panels outside of clicking the invoking button again. We could use close buttons or explore other options. 

- I am also hoping that we can **reduce behavior change** that users have to expect across different action buttons. For example, if the first couple of buttons in a grouped set of action buttons open a tall panel, a user will expect the other ones to follow suit (how it currently works with the first 4 buttons in the left panel). If the next set starts opening a menu (like the save button), as a best practice we should have the other buttons (open existing, open new) follow a similar pattern of opening a menu or panel (currently the create new button is a sharp behavior change). 

I think I just wrote an essay sorry, but I highlighted some of the UX best practices we can explore for beta 2.

**Comment by mitc7862** [comment]
@arjavbadjatiya I'm on the fence about adding a third-level drill in for the symbol styler. It could work, but I also think we would need to reconsider how flow-manager navigation would work to help orient users. Perhaps a better approach would be to place the Symbol Style floating panel over the Style Properties panel instead of over the map… I will explore what this would look like. 

I don't think putting the legend in it's own panel makes much sense at all. I feel it elevates its relative importance too much… and I think it's too permanent. I think a better approach would be to  make the change that @asangma proposed above, and only let one or the other—layers or legend—show at any given time. This will bring it closer to what Jeremy suggested by collapsing the layers dynamically.

**Comment by arjavbadjatiya** [comment]
@mitc7862 Legend currently has its own panel, that's what I based it on. If we're planning to club layer and legend together, then this approach will change.

**Comment by asangma** [comment]
#130 could be addressed by this.

**Comment by kat10140** [comment]
VERFEEEEEEE
