### ISSUE TITLE
Bug: Demo: loading and disabled not working on Tip Manager

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#592]
### Summary
Loading and disabled states aren't working on tip manager in the demo

### Actual Behavior
Dey don't work

### Expected Behavior
Loading and disabled states to werk

**Comment by pr3tori4n** [comment]
@kat10140 it doesn't look like loading or disabled states were ever added for these two components. Right now the toggle buttons are coded to show up on every page, but for any components that don't have these states they won't do anything.

## Options
* If we want to add those states to these components, that'd be an enhancement.
* We could adjust the toggle button logic so that it doesn't show up on some pages.
* We could leave it as is. It is actually indicative that the loading and disabled props don't change the component, which is expected behavior unless we added them.

**Comment by kat10140** [comment]
I think we should have toggle button logic. Loading and disabled are also on the home page and don't have a function

**Comment by kat10140** [comment]
New issue: https://github.com/Esri/calcite-app-components/issues/609
Closing
