### ISSUE TITLE
Bug: calcite-pick-list issues after upgrade

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#919]
### Summary
Still happening in 5.7.0 and beta.22. I think it started with 5.6.0.

The very first time in my browser session when I open the pick-list with check boxes all works fine. Any time after that I don't see check boxes.

First time:
<img src=https://user-images.githubusercontent.com/44481292/78587052-45cb5a80-77f1-11ea-96b0-5f035d7891d7.png width=200/>

After that:
<img src=https://user-images.githubusercontent.com/44481292/78587102-554aa380-77f1-11ea-8f21-7c0fff223ef4.png width=200/>

But I can click on a field and the selection works. Just doesn't show a checkbox.

If I start up my browser session with a pick-list with radio buttons it also works the first time.

<img src=https://user-images.githubusercontent.com/44481292/78587311-9d69c600-77f1-11ea-9a5d-36c724a102d0.png width=200/>

After that I no longer see the radio buttons and the selection change does not work.
<img src=https://user-images.githubusercontent.com/44481292/78587393-ba9e9480-77f1-11ea-814a-32591216c2fc.png width=200/>

If I start with check boxes or radio buttons it works once and then I then do the same again or the opposite, like open with check boxes after radio buttons, it doesn't work anymore.
Even if I destroy the smartMapping component and create it again it won't work anymore. 

test case:
http://devext.arcgis.com/apps/mapviewer/index.html?urls=https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2
Click on 'Styles' on the right tool bar, then click on '+ Field'.

### Reproduction Steps

1.

**Comment by jcfranco** [comment]
This bug is a regression caused by Stencil's new compiler, which the default since v1.11.0 (calcite-app-components picked it up in 5.6.0). FWIW, I think this has been an issue since 1.9.0, but went unnoticed because we weren't testing with the latest compiler flag. I think I've narrowed it down to the next compiler affecting the component lifecycle slightly and some assumptions made by the `MutationObserver` logic in the list. I'll do a little bit more testing and will submit a PR if everything looks 👌:sunglasses:.

@AdelheidF In the meantime, I think setting `icon` on the item-generating code could help as a workaround.

**Comment by AdelheidF** [comment]
> I think setting icon on the item-generating code could help as a workaround.

Yes, this solves the issue with the missing icons. But pick-list with multiple=false seems to have no effect. I still can select multiple items.

**Comment by jcfranco** [comment]
@AdelheidF Thanks for testing. Luckily, I've installed a fix for this that addresses the underlying issue.

**Comment by AdelheidF** [comment]
With newly released 5.7.1 calcite-app-components (tested locally) the issue with the pick-list are fixed, but now drag-n-drop doesn't work anymore in value-list. That worked with 5.7.0.

**Comment by AdelheidF** [comment]
5.7.2 DND works again

**Comment by AdelheidF** [comment]
verified all locally

**Comment by jcfranco** [comment]
@AdelheidF Thanks! 🎉
